---
arch:
  - aarch64
  - amd64
description: A minimalist GPodder server, using the same API, for self-hosting
ingress: true
init: false
name: "oPodSync"
panel_icon: "mdi:bookmark-music"
port_description:
  "8099/tcp": Web interface
ports:
  "8099/tcp": 3481
slug: "opodsync"
startup: application
url: https://github.com/Blackhex/home-assistant-addons/tree/main/opodsync
version: dev
